apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: react-app-bago-local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app-bago-local
  template:
    metadata:
      labels:
        app: react-app-bago-local
    spec:
      containers:
        - name: react-app
          image: juanse793/bagolocal:latest
          ports:
            - containerPort: 2000
