apiVersion: v1
kind: Service
metadata:
  name: react-app-bago-local
spec:
  type: NodePort
  selector:
    app: react-app-bago-local
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 2000
      nodePort: 30486
